# Generated by Django 3.0.6 on 2020-09-10 11:21

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DfJobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=120, unique=True)),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'DF Job Category',
            },
        ),
        migrations.CreateModel(
            name='DfJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Title', models.CharField(max_length=120)),
                ('Job_slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='Job_Title', unique_with=('Create_date__month',))),
                ('Job_Description', models.TextField()),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwWineType_DfJobs', to='manage_jobs.DfJobCategory')),
            ],
            options={
                'verbose_name_plural': 'DF Job Category',
            },
        ),
    ]
