# Generated by Django 3.0.6 on 2020-09-19 12:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dfjobs',
            options={'verbose_name_plural': 'DF Jobs'},
        ),
        migrations.CreateModel(
            name='DfJobApplaication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('contact_no', models.BigIntegerField()),
                ('Application_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Job_DfJobs', to='manage_jobs.DfJobs')),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AwWineType_DfApplay', to='manage_jobs.DfJobCategory')),
            ],
            options={
                'verbose_name_plural': 'DF Job Applaication',
            },
        ),
    ]
