# Generated by Django 3.0.6 on 2020-09-19 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_jobs', '0002_auto_20200919_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dfjobapplaication',
            name='Job',
        ),
        migrations.RemoveField(
            model_name='dfjobapplaication',
            name='job_category',
        ),
        migrations.AddField(
            model_name='dfjobapplaication',
            name='Job_title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Job_DfJobs', to='manage_jobs.DfJobs'),
        ),
        migrations.AddField(
            model_name='dfjobapplaication',
            name='job_cate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='AwWineType_DfApplay', to='manage_jobs.DfJobCategory'),
        ),
    ]
