# Generated by Django 3.0.6 on 2020-09-22 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DfPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Package_Type', models.CharField(choices=[('S', 'Start'), ('B', 'Business'), ('P', 'Professional'), ('M', 'Max')], max_length=120)),
                ('Price', models.FloatField(default=0)),
                ('Start', models.BooleanField(default=True)),
                ('Create_Date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'DF Price',
            },
        ),
    ]
