# Generated by Django 3.0.6 on 2020-09-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfprice',
            name='Duration_Type',
            field=models.CharField(blank=True, choices=[('D', 'Days'), ('M', 'Mohnth'), ('Y', 'Year')], max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dfprice',
            name='Duration_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dfprice',
            name='Package_Type',
            field=models.CharField(choices=[('S', 'Start'), ('B', 'Business'), ('P', 'Professional'), ('M', 'Max')], max_length=120, unique=True),
        ),
    ]
