# Generated by Django 3.0.6 on 2020-09-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pricing', '0002_auto_20200922_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfprice',
            name='Duration_Type',
            field=models.CharField(blank=True, choices=[('D', 'Days'), ('M', 'Mohnth'), ('Y', 'Year')], max_length=120, null=True),
        ),
    ]
