# Generated by Django 3.0.6 on 2020-09-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pricing', '0003_auto_20200922_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfprice',
            name='priyorty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dfprice',
            name='Duration_Type',
            field=models.CharField(blank=True, choices=[('D', 'Days'), ('M', 'Month'), ('Y', 'Year')], max_length=120, null=True),
        ),
    ]
