# Generated by Django 3.0.6 on 2020-09-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pricing', '0004_auto_20200922_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='DfPackageName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('keyword', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'DF Package',
            },
        ),
        migrations.AlterField(
            model_name='dfprice',
            name='Package_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_pricing.DfPackageName'),
        ),
    ]
