# Generated by Django 3.0.6 on 2020-09-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pricing', '0006_auto_20200922_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dfprice',
            name='priyorty',
        ),
    ]
