# Generated by Django 3.0.6 on 2020-09-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pricing', '0007_remove_dfprice_priyorty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dfprice',
            name='Package_Type',
        ),
        migrations.AddField(
            model_name='dfprice',
            name='PackageType',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
