# Generated by Django 3.0.6 on 2020-09-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pricing', '0009_auto_20200922_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfprice',
            name='Orders_set',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='dfprice',
            name='Package_Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_pricing.DfPackageName', unique=True),
        ),
    ]
