# Generated by Django 3.0.6 on 2020-09-22 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pricing', '0010_auto_20200922_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfprice',
            name='Package_Type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_pricing.DfPackageName'),
        ),
    ]
