# Generated by Django 3.0.6 on 2020-07-28 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_locations', '0019_auto_20200420_1405'),
        ('accounts', '0005_auto_20200410_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='DfVoiceFaqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField(blank=True, null=True)),
                ('Craete_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('DfUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.DfUser')),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_locations.DfBusinessLocation')),
            ],
            options={
                'verbose_name_plural': 'DF Voice Faqs',
            },
        ),
    ]
