# Generated by Django 3.0.4 on 2020-04-10 09:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manage_locations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20200410_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='DfLocationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to=manage_locations.models.user_directory_path_for_other_image)),
                ('Craete_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Business_Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.DfUser')),
            ],
            options={
                'verbose_name_plural': 'DF Location Other Image',
            },
        ),
        migrations.CreateModel(
            name='DfBusinessLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_Code', models.CharField(max_length=50)),
                ('Business_Logo', models.ImageField(blank=True, null=True, upload_to=manage_locations.models.user_directory_path)),
                ('Location_name', models.CharField(blank=True, max_length=120, null=True)),
                ('Business_catugory', models.CharField(blank=True, max_length=120, null=True)),
                ('Additional_catugory', models.TextField(blank=True, null=True)),
                ('Address_1', models.TextField(blank=True, max_length=120, null=True)),
                ('Address_2', models.TextField(blank=True, max_length=120, null=True)),
                ('Country', models.CharField(blank=True, max_length=120, null=True)),
                ('State', models.CharField(blank=True, max_length=120, null=True)),
                ('City', models.CharField(blank=True, max_length=120, null=True)),
                ('Zipcode', models.IntegerField(blank=True, null=True)),
                ('Phone_no', models.IntegerField(blank=True, null=True)),
                ('Website', models.URLField(blank=True, null=True)),
                ('Business_Owner_Name', models.CharField(blank=True, max_length=120, null=True)),
                ('Owner_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Business_Tagline', models.CharField(blank=True, max_length=120, null=True)),
                ('Year_Of_Incorporation', models.IntegerField()),
                ('About_Business', models.IntegerField()),
                ('Facebook_Profile', models.CharField(blank=True, max_length=120, null=True)),
                ('Instagram_Profile', models.CharField(blank=True, max_length=120, null=True)),
                ('Twitter_Profile', models.CharField(blank=True, max_length=120, null=True)),
                ('Operating_Hours_Monday', models.CharField(blank=True, max_length=120, null=True)),
                ('Operating_Hours_Tuseday', models.CharField(blank=True, max_length=120, null=True)),
                ('Operating_Hours_Wednesday', models.CharField(blank=True, max_length=120, null=True)),
                ('Operating_Hours_Thursday', models.CharField(blank=True, max_length=120, null=True)),
                ('Operating_Hours_Friday', models.CharField(blank=True, max_length=120, null=True)),
                ('Operating_Hours_Saturday', models.CharField(blank=True, max_length=120, null=True)),
                ('Operating_Hours_Sunday', models.CharField(blank=True, max_length=120, null=True)),
                ('Business_Cover_Image', models.ImageField(upload_to=manage_locations.models.user_directory_path_for_banner)),
                ('Craete_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Update_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('DfUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.DfUser')),
            ],
            options={
                'verbose_name_plural': 'DF Business Location',
            },
        ),
    ]
