# Generated by Django 3.0.4 on 2020-04-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_locations', '0002_auto_20200410_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfbusinesslocation',
            name='About_Business',
            field=models.TextField(blank=True, null=True),
        ),
    ]
