# Generated by Django 3.0.4 on 2020-04-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_locations', '0004_auto_20200410_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dfbusinesslocation',
            old_name='Business_catugory',
            new_name='Business_category',
        ),
    ]
