# Generated by Django 3.0.4 on 2020-04-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_locations', '0006_auto_20200411_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='DfLocationPaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Method', models.CharField(blank=True, max_length=20, null=True)),
                ('Business_Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Df_location_payments', to='manage_locations.DfBusinessLocation')),
            ],
            options={
                'verbose_name_plural': 'DF Location Payment Method',
            },
        ),
    ]
