# Generated by Django 3.0.4 on 2020-04-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200410_1503'),
        ('social_media_platforms', '0002_auto_20200413_1243'),
        ('manage_locations', '0008_dflocationconnectplatfor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DfLocationConnectPlatfor',
            new_name='DfLocationConnectPlatform',
        ),
    ]
