# Generated by Django 3.0.5 on 2020-04-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_locations', '0009_auto_20200413_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dfbusinesslocation',
            name='Operating_Hours_Friday',
        ),
        migrations.RemoveField(
            model_name='dfbusinesslocation',
            name='Operating_Hours_Monday',
        ),
        migrations.RemoveField(
            model_name='dfbusinesslocation',
            name='Operating_Hours_Saturday',
        ),
        migrations.RemoveField(
            model_name='dfbusinesslocation',
            name='Operating_Hours_Sunday',
        ),
        migrations.RemoveField(
            model_name='dfbusinesslocation',
            name='Operating_Hours_Thursday',
        ),
        migrations.RemoveField(
            model_name='dfbusinesslocation',
            name='Operating_Hours_Tuseday',
        ),
        migrations.RemoveField(
            model_name='dfbusinesslocation',
            name='Operating_Hours_Wednesday',
        ),
    ]
