# Generated by Django 3.0.5 on 2020-04-16 09:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_locations', '0010_auto_20200416_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='DfLocationOpenHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(blank=True, max_length=20, null=True)),
                ('Type', models.CharField(blank=True, max_length=20, null=True)),
                ('Open_status', models.CharField(blank=True, max_length=20, null=True)),
                ('start_time_1', models.CharField(blank=True, max_length=20, null=True)),
                ('end_time_1', models.CharField(blank=True, max_length=20, null=True)),
                ('start_time_2', models.CharField(blank=True, max_length=20, null=True)),
                ('Update_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Business_Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Df_location_poen_houre', to='manage_locations.DfBusinessLocation')),
            ],
            options={
                'verbose_name_plural': 'DF Location Open Hours',
            },
        ),
    ]
