# Generated by Django 3.0.5 on 2020-04-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_locations', '0011_dflocationopenhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='dflocationopenhours',
            name='end_time_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
