# Generated by Django 3.0.5 on 2020-04-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_locations', '0012_dflocationopenhours_end_time_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfbusinesslocation',
            name='Do_not_publish_my_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dfbusinesslocation',
            name='Franchise_Location',
            field=models.BooleanField(default=True),
        ),
    ]
