# Generated by Django 3.0.5 on 2020-04-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_locations', '0013_auto_20200416_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dfbusinesslocation',
            old_name='Do_not_publish_my_address',
            new_name='Do_Not_Publish_My_Address',
        ),
    ]
