# Generated by Django 3.0.5 on 2020-04-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_locations', '0015_auto_20200416_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='dflocationopenhours',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
