# Generated by Django 3.0.5 on 2020-04-20 11:02

from django.db import migrations, models
import manage_locations.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_locations', '0016_dflocationopenhours_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfbusinesslocation',
            name='Business_Logo',
            field=models.FileField(blank=True, null=True, upload_to=manage_locations.models.user_directory_path),
        ),
    ]
