# Generated by Django 3.0.5 on 2020-04-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_locations', '0018_auto_20200420_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dflocationopenhours',
            name='Business_Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Df_location_poen_hour', to='manage_locations.DfBusinessLocation'),
        ),
    ]
