# Generated by Django 3.0.4 on 2020-04-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_platforms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dfsocialmedia',
            old_name='connect_status',
            new_name='Connect_status',
        ),
        migrations.RenameField(
            model_name='dfsocialmedia',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='dfsocialmedia',
            old_name='username',
            new_name='Username',
        ),
    ]
