# Generated by Django 3.0.6 on 2020-09-05 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('queryes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DfQueryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Your_Email', models.CharField(max_length=20)),
                ('Message', models.TextField()),
                ('Other_Data', models.TextField(blank=True, default='', null=True)),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'DF Query',
            },
        ),
        migrations.DeleteModel(
            name='DfQuery',
        ),
    ]
