# Generated by Django 3.0.6 on 2020-09-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryes', '0002_auto_20200905_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfqueryinfo',
            name='Name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='dfqueryinfo',
            name='Your_Email',
            field=models.CharField(max_length=120),
        ),
    ]
