# Generated by Django 3.0.6 on 2020-09-10 07:54

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import manage_bloges.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DfBlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Title', models.CharField(max_length=120)),
                ('Blog_slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='Blog_Title', unique_with=('Create_date__month',))),
                ('Blog_Image', models.ImageField(upload_to=manage_bloges.models.user_directory_path_for_banner)),
                ('Message', models.TextField()),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'DF Blogs',
            },
        ),
    ]
