# Generated by Django 3.0.6 on 2020-08-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200410_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dfuser',
            old_name='Business_name',
            new_name='Company_name',
        ),
        migrations.RenameField(
            model_name='dfuser',
            old_name='City',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='dfuser',
            old_name='State',
            new_name='Pnone',
        ),
        migrations.RemoveField(
            model_name='dfuser',
            name='Address',
        ),
    ]
