# Generated by Django 3.0.6 on 2020-08-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200806_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfuser',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
