# Generated by Django 3.0.4 on 2020-04-20 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_locations', '0009_auto_20200413_1648'),
        ('accounts', '0005_auto_20200410_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='DfLocationReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Social_Plateform', models.CharField(blank=True, max_length=50, null=True)),
                ('User_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Reating', models.CharField(blank=True, max_length=50, null=True)),
                ('Review', models.TextField(blank=True, null=True)),
                ('User_Image_URL', models.TextField(blank=True, max_length=50, null=True)),
                ('Review_dateTime', models.CharField(blank=True, max_length=50, null=True)),
                ('Craete_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Business_Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_locations.DfBusinessLocation')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.DfUser')),
            ],
            options={
                'verbose_name_plural': 'DF Business Reviews',
            },
        ),
    ]
