# Generated by Django 3.0.4 on 2020-04-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dflocationreviews',
            old_name='User',
            new_name='Df_User',
        ),
    ]
