# Generated by Django 3.0.6 on 2020-09-22 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_auto_20200821_1621'),
        ('manage_pricing', '0004_auto_20200922_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='DfOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.CharField(max_length=120, unique=True)),
                ('Final_Amount', models.FloatField(default=0)),
                ('Duration_Type', models.CharField(blank=True, max_length=120, null=True)),
                ('Duration_Time', models.IntegerField(default=0)),
                ('Create_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Payment', models.BooleanField(default=False)),
                ('Payment_Type', models.CharField(max_length=120)),
                ('Transaction_id', models.CharField(blank=True, max_length=120, null=True)),
                ('Payment_Date', models.DateTimeField(blank=True, null=True)),
                ('Active', models.BooleanField(default=False)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('DfUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.DfUser')),
                ('Package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_pricing.DfPrice')),
            ],
            options={
                'verbose_name_plural': 'DF Orders',
            },
        ),
    ]
