# Generated by Django 3.0.6 on 2020-09-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_orders_and_payments', '0003_auto_20200922_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dforders',
            name='End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dforders',
            name='Payment_Type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='dforders',
            name='Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
