# Generated by Django 3.0.6 on 2020-09-22 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_pricing', '0011_auto_20200922_1434'),
        ('accounts', '0008_auto_20200821_1621'),
        ('manage_orders_and_payments', '0004_auto_20200922_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dforders',
            name='DfUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.DfUser'),
        ),
        migrations.AlterField(
            model_name='dforders',
            name='Duration_Type',
            field=models.CharField(choices=[('D', 'Days'), ('M', 'Month'), ('Y', 'Year')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='dforders',
            name='Order_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dforders',
            name='Package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_pricing.DfPrice'),
        ),
    ]
