# Generated by Django 3.0.6 on 2020-09-23 06:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200821_1621'),
        ('manage_pricing', '0011_auto_20200922_1434'),
        ('manage_orders_and_payments', '0005_auto_20200922_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dforders',
            name='DfUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.DfUser'),
        ),
        migrations.AlterField(
            model_name='dforders',
            name='Duration_Type',
            field=models.CharField(blank=True, choices=[('D', 'Days'), ('M', 'Month'), ('Y', 'Year')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='dforders',
            name='Package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_pricing.DfPrice'),
        ),
        migrations.CreateModel(
            name='DfOrdersAndPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('Final_Amount', models.FloatField(default=0)),
                ('Duration_Type', models.CharField(choices=[('D', 'Days'), ('M', 'Month'), ('Y', 'Year')], max_length=120)),
                ('Duration_Time', models.IntegerField()),
                ('Create_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Payment', models.BooleanField(default=False)),
                ('Payment_Type', models.CharField(blank=True, max_length=120, null=True)),
                ('Transaction_id', models.CharField(blank=True, max_length=120, null=True)),
                ('Payment_Date', models.DateTimeField(blank=True, null=True)),
                ('Active', models.BooleanField(default=False)),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('DfUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.DfUser')),
                ('Package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_pricing.DfPrice')),
            ],
            options={
                'verbose_name_plural': 'DF Orders And Payment',
            },
        ),
    ]
