# Generated by Django 3.0.6 on 2020-08-10 07:39

from django.db import migrations, models
import manage_campus.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfcampus',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=manage_campus.models.user_directory_path_for_banner),
        ),
    ]
