# Generated by Django 3.0.6 on 2020-08-10 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manage_campus.models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_locations', '0019_auto_20200420_1405'),
        ('accounts', '0007_auto_20200806_1201'),
        ('manage_campus', '0002_auto_20200810_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='DfCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Sent_from', models.CharField(max_length=150)),
                ('replay_to', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to=manage_campus.models.user_directory_path_for_banner)),
                ('sms_message', models.TextField(blank=True, null=True)),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('BusinessLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_locations.DfBusinessLocation')),
                ('DfUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.DfUser')),
            ],
            options={
                'verbose_name_plural': 'DF Campaign',
            },
        ),
        migrations.DeleteModel(
            name='DfCampus',
        ),
    ]
