# Generated by Django 3.0.6 on 2020-08-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_campus', '0003_auto_20200810_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfcampaign',
            name='Extera_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
