# Generated by Django 3.0.6 on 2020-08-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_campus', '0004_dfcampaign_extera_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfcampaign',
            name='Head',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dfcampaign',
            name='Subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
