# Generated by Django 3.0.6 on 2020-08-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_campus', '0005_auto_20200811_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfcampaign',
            name='Head',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dfcampaign',
            name='Sent_from',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dfcampaign',
            name='Subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dfcampaign',
            name='Title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dfcampaign',
            name='replay_to',
            field=models.CharField(max_length=500),
        ),
    ]
