# Generated by Django 3.0.6 on 2020-08-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_campus', '0007_dfuseremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfuseremail',
            name='Contact',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
