# Generated by Django 3.0.6 on 2020-09-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dffaqs',
            options={'verbose_name_plural': 'DF Question'},
        ),
    ]
