# Generated by Django 3.0.4 on 2020-04-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_dropdown_value', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DfCity',
        ),
    ]
